Bloggie.Web/Controllers/AdminBlogPostsController.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bloggie.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // get tags from repository
            var tags = await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            // Map view model to domain model
            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };

            // Map Tags from selected tags
            var selectedTags = new List<Tag>();
            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }

            // Mapping tags back to domain model
            blogPost.Tags = selectedTags;


            await blogPostRepository.AddAsync(blogPost);

            return RedirectToAction("Add");
        }


        [HttpGet]
        public async Task<IActionResult> List()
        {
            // Call the repository 
            var blogPosts = await blogPostRepository.GetAllAsync();

            return View(blogPosts);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            // Retrieve the result from the repository 
            var blogPost = await blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (blogPost != null)
            {
                // map the domain model into the view model
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);

            }

            // pass data to view
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            // map view model back to domain model
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible
            };

            // Map tags into domain model

            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTags;

            // Submit information to repository to update
            var updatedBlog =  await blogPostRepository.UpdateAsync(blogPostDomainModel);

            if (updatedBlog != null)
            {
                // Show success notification
                return RedirectToAction("Edit");
            }

            // Show error notification
            return RedirectToAction("Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            // Talk to repository to delete this blog post and tags
            var deletedBlogPost = await blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deletedBlogPost != null)
            {
                // Show success notification
                return RedirectToAction("List");
            }

            // Show error notification
            return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
        }
    }
}

Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            ValidateAddTagRequest(addTagRequest);
            
            if (ModelState.IsValid == false)
            {
                return View();
            }

            // Mapping AddTagRequest to Tag domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

            await tagRepository.AddAsync(tag);

            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(
            string? searchQuery, 
            string? sortBy, 
            string? sortDirection,
            int pageSize = 3,
            int pageNumber = 1)
        {
            var totalRecords = await tagRepository.CountAsync();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            if (pageNumber > totalPages)
            {
                pageNumber--;
            }

            if (pageNumber < 1)
            {
                pageNumber++;
            }


            ViewBag.TotalPages = totalPages;
            ViewBag.SearchQuery = searchQuery;
            ViewBag.SortBy = sortBy;
            ViewBag.SortDirection = sortDirection;
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;

            // use dbContext to read the tags
            var tags = await tagRepository.GetAllAsync(searchQuery, sortBy, sortDirection, pageNumber, pageSize);

            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await tagRepository.GetAsync(id);
            
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

                return View(editTagRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await tagRepository.UpdateAsync(tag);

            if (updatedTag != null)
            {
                // Show success notification
            }
            else
            {
                // Show error notification
            }

            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);

            if (deletedTag != null)
            {
                // Show success notification
                return RedirectToAction("List");
            }

            // Show an error notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }


        private void ValidateAddTagRequest(AddTagRequest request)
        {
            if (request.Name is not null && request.DisplayName is not null)
            {
                if (request.Name == request.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name cannot be the same as DisplayName");
                }
            }
        }
    }
}

Bloggie.Web/Controllers/TopicsController.cs
using Microsoft.AspNetCore.Mvc;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;

namespace Bloggie.Web.Controllers
{
    public class TopicsController : Controller
    {
        private readonly IBlogPostRepository blogPostRepository;

        public TopicsController(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        public async Task<IActionResult> WaterEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Water Energy");
            return View(blogPosts);
        }


        public async Task<IActionResult> WindEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Wind Energy");
            return View(blogPosts);
        }

        public async Task<IActionResult> SolarEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Solar Energy");
            return View(blogPosts);
        }

        public async Task<IActionResult> GeothermalEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Geothermal Energy");
            return View(blogPosts);
        }

        public async Task<IActionResult> BiomassEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Biomass Energy");
            return View(blogPosts);
        }

        public async Task<IActionResult> FutureEnergy()
        {
            var blogPosts = await blogPostRepository.GetByTagAsync("Future Energy");
            return View(blogPosts);
        }
    }
}

Bloggie.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> signInManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData[@Resource.HomePage] - @Resource.RenewableAndSustainableEnergy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Resource.RenewableAndSustainableEnergy</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@Resource.HomePage</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))

                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @Resource.Admin
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">@Resource.AddTag</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">@Resource.ShowAllTags</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="Add">@Resource.AddNewPost</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="List">@Resource.AllPosts</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminUsers" asp-action="List">@Resource.AllUsers</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto d-flex align-items-center gap-3">
                        @if (signInManager.IsSignedIn(User))

                        {
                            <li class="nav-item">
                                <span class="nav-link"><i class="fas fa-user-circle"></i> @User?.Identity?.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-danger btn-sm ms-2 d-flex align-items-center gap-1" asp-area="" asp-controller="Account" asp-action="Logout">
                                    <i class="fas fa-sign-out-alt"></i> @Resource.Logout
                                </a>
                            </li>
                        }

                        else

                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary btn-sm ms-2 d-flex align-items-center gap-1" asp-area="" asp-controller="Account" asp-action="Login">
                                    <i class="fas fa-sign-in-alt"></i> @Resource.Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-success btn-sm ms-2 d-flex align-items-center gap-1" asp-area="" asp-controller="Account" asp-action="Register">
                                    <i class="fas fa-user-plus"></i> @Resource.Register
                                </a>
                            </li>
                        }

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-globe"></i> 
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="languageDropdown">
                                <li>
                                    <form asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang ="en">
                                        <input type="hidden" name="culture" value="en" />
                                        <button type="submit" class="dropdown-item">
                                            @if (Thread.CurrentThread.CurrentCulture.ToString() == "en")
                                            {
                                                <p class="text-success">English</p>
                                            }
                                            else
                                            {
                                                 <p>English</p>
                                            }
                                        </button>
                                    </form>
                                </li>
                                <li>
                                    <form asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang ="tr">
                                        <input type="hidden" name="culture" value="tr" />
                                        <button type="submit" class="dropdown-item">
                                            @if (Thread.CurrentThread.CurrentCulture.ToString() == "tr")
                                            {
                                                <p class="text-success">Türkçe</p>
                                            }
                                            else
                                            {
                                                 <p>Türkçe</p>
                                            }
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>

    </header>

    <main class="flex-grow-1 py-5 mt-3">
        @RenderBody()
    </main>


    <footer class="footer bg-light text-muted text-center ">
        <div class="container">
            &copy; 2024 - @Resource.RenewableAndSustainableEnergy - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Resource.Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @if (IsSectionDefined("Scripts"))

    {
        @RenderSection("Scripts", required: false)
    }
</body>
</html>

Bloggie.Web/Views/Shared/_SidebarPartialView.cshtml
<nav id="sidebarMenu" class="sidebar bg-white border-end flex-shrink-0" style="width: 250px;">
    <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
            <a asp-controller="Topics" asp-action="WaterEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-water fa-fw me-3"></i><span>@Resource.WaterEnergy</span>
            </a>
            <a asp-controller="Topics" asp-action="WindEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-wind fa-fw me-3"></i><span>@Resource.WindEnergy</span>
            </a>
            <a asp-controller="Topics" asp-action="SolarEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-sun fa-fw me-3"></i><span>@Resource.SolarEnergy</span>
            </a>
            <a asp-controller="Topics" asp-action="GeothermalEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-mountain fa-fw me-3"></i><span>@Resource.GeothermalEnergy</span>
            </a>
            <a asp-controller="Topics" asp-action="BiomassEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-leaf fa-fw me-3"></i><span>@Resource.BiomassEnergy</span>
            </a>
            <a asp-controller="Topics" asp-action="FutureEnergy" class="list-group-item list-group-item-action py-2 ripple">
                <i class="fas fa-globe fa-fw me-3"></i><span>@Resource.TheFutureOfRenewableEnergySources</span>
            </a>
        </div>
    </div>
</nav>